name: rps_mobx
description: DevFest Vizag

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+7
  flutter_mobx: ^2.0.6+3
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+2
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/  
